[features]
seeds = false
skip-lint = false

[programs.localnet]
casinoos_escrow = "Casin0s111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"
